# -*- coding: utf-8 -*-
"""Entregable 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nB7w-9BrJgTWevZmpIsRs0EXAEF7h7bm

## ***Dataset Cancer de Mama***.

# ***Desarollo***

Comenzamos importando las librerías que utilizaremos durante el desarrollo del proyecto. Además, importamos el dataset:
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

DATA_PATH = Path("cancer_de_mama.csv")

df = pd.read_csv(DATA_PATH)
df.head()

"""Podemos notar que las escalas de algunas variables son distintas. Sin embargo, antes de escalar haremos el respectivo análisis exploratorio para observar los comportamientos originales."""

df.shape

"""Estamos ante la presencia de un dataset con 569 filas y 32 columnas (variables).

Ahora bien, identifiquemos qué tipos de variables tenemos, pues de esta forma sabremos como abordar cada una dependiendo si son numéricas, categóricas, booleanas, etc.
"""

df.dtypes

"""Todas nuestras variables son numéricas de tipo float (números reales) salvo la variable "diagnosis", pues esta es de tipo categórica debido a que nos indica si la masa de la mama es benigna o maligna. Incluso podríamos transformarla en booleana para facilitar el análisis.

Por otra parte, veamos algunos estadísticos que nos muestren un primer comportamiento de algunas variables:
"""

df.describe()

"""A priori, podemos observar lo siguiente:

1. No parece haber datos nulos (de todas formas, lo comprobaremos más adelante), pues las cantidades totales son exactamente las mismas salvo por la variable "id", sin embargo, esta no aportará al análisis por ser un identificador único.
2. Las desviaciones estándar de algunas variables parecen ser exageradamente altas, lo cual nos da a entender que posiblemente estamos ante la presencia de datos atípicos.

Verifiquemos si existen datos nulos:
"""

df.isnull().sum()

"""En efecto, el dataset está completo, así que no debemos realizar ningún tipo de imputación o eliminación de filas y/o columnas, lo cual nos conviene aún más.

Por otra parte, busquemos posibles datos o entradas duplicadas:
"""

df[df.duplicated()]

"""De esta forma, confirmamos entonces que no existen datos repetidos.

## ***Restricciones para Variables***

Debido a que nuestro dataset es tan grande, no es eficiente revisar entrada a entrada, por lo tanto, no tenemos certeza de que los datos tengan sentido de acuerdo a las variables. Para ello, buscaremos restringirlas, de manera que cada columna almacene valores acordes a su naturaleza (que no haya fechas en lugares de números, que las booleanas si lo sean, entre otros).
"""

df_num = df.drop(columns=["id", "diagnosis"])

mask = df_num.apply(lambda col: col.apply(lambda x: isinstance(x, (float, np.float64))))
df_num[~mask.all(axis=1)]

df[~df["diagnosis"].isin(["M", "B"])]

"""De esta forma, la naturaleza de los estados no presenta problemas, es decir, las variables de tipo "float" lo son todas, y la variable "diagnosis" solo posee valores de "M" y "B".

Una vez realizada la exploración inicial, procedemos a realizar un análisis univariado y posteriormente uno bivariado:

# ***Análisis Univariado***

Comenzaremos analizando las variables numéricas. Observaremos sus distribuciones, variabilidad y outliers.
"""

num_cols = df_num.select_dtypes(include=["int64", "float64"]).columns

df[num_cols].hist(figsize=(20, 15), bins=30, edgecolor="black", color = "salmon")
plt.tight_layout()
plt.show()

"""Observamos que las variables, en su mayoría, poseen asimetrías positivas, lo cual indica la presencia de valores atípicos. En este caso, podría ser bastante peligroso eliminarlos debido a que el dataset consta de datos experimentales, por lo tanto todos los valores pueden ser posibles de acuerdo a las personas a las que se les hace las mediciones.

Por otro lado, también tenemos variables cuya distribución es aproximadamente normal, por tanto, los outliers son típicamente escasos.

Veamos como se distribuyen los datos atípicos mediante boxplots:
"""

df[num_cols].plot(kind="box", subplots=True, figsize=(20, 15), layout=(7, 5), color = "salmon")
plt.tight_layout()
plt.show()

"""En efecto, todas las variables (salvo "concave points_worst") poseen datos atípicos, y tal parece ser que en una alta proporción. Sin embargo, como lo mencionamos anteriormente, no conviene eliminarlos por el hecho de ser datos clínicos experimentales, por tanto, cualquier medición puede ser posible.

Analicemos ahora la variable categórica:
"""

df["diagnosis"].value_counts().plot(kind="bar", edgecolor="black", color="salmon")
plt.title("diagnosis")
plt.ylabel("frecuencia")
plt.xticks(rotation=0)
plt.show()

"""De este modo, observamos que el número de masas benignas supera la cantidad de masas malignas, lo cual clínicamente es esperanzador. La idea será analizar como influyen las demás variables en el diagnóstico del cancer de mama.

# ***Análisis Bivariado***

A continuación veremos que relaciones existen entre dos variables numéricas, de modo que podamos observar si una puede explicar a otra. Veamos entonces las correlaciones y sus respectivos diagramas de dispersión:
"""

plt.figure(figsize=(24,20))
sns.heatmap(df_num.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Matriz de correlación - Pearson")
plt.show()

"""Los colores cálidos muestran una relación aparentemente lineal debido a la correlación de Pearson, de esta manera podemos afirmar que existen variables que explican otras.

Por otro lado, podemos eliminar redundancias debido a que existen correlaciones de 0.98 en adelante (color rojo), esto nos da a entender que seguramente las variables explican (o son), en esencia, lo mismo.

Observemos los diagramas de dispersión, ya que no podemos fiarnos solo de los valores de la matriz de correlación, pues si existen datos atípicos muy extremos puede suceder que afecte la forma de los datos:
"""

sns.pairplot(df[num_cols], diag_kind="hist", plot_kws={"color": "salmon"}, diag_kws={"color": "steelblue"})

plt.show()

"""En efecto, los diagramas de dispersión reflejan relaciones lineales entre las variables que están altamente relacionadas, por tanto, el coeficiente de correlación de Pearson es adecuado para modelar la explicación entre variables.

Veamos como influyen las variables numéricas en la variables categórica que describe el diagnóstico mediante boxplots:
"""

fig, axes = plt.subplots(nrows=6, ncols=5, figsize=(20, 15))
axes = axes.flatten()

for i, col in enumerate(num_cols):
    df.boxplot(column=col, by="diagnosis", ax=axes[i], color = "salmon")
    axes[i].set_title(col, fontsize=9)
    axes[i].set_xlabel("")

for j in range(i+1, len(axes)):
    axes[j].set_visible(False)

plt.suptitle("")
plt.tight_layout()
plt.show()

"""En general, observamos que los boxplots no se solapan mucho, esto indica que existen diferencias significativas entre los niveles "maligno" (M) y "benigno" (B) de la variable "diagnosis". De esta forma, podríamos inferir a priori, que el comportamiento de las variables es distinto para cada nivel, así que debería ser relativamente fácil distinguir entre ambas clases. Esto sugiere que las variables numéricas tienen un alto poder discriminante, lo que implica que un modelo de clasificación podría separar con buena precisión los casos malignos de los benignos basándose en estas características."""

# 1. Separar variables predictoras y objetivo
X = df.drop("diagnosis", axis=1)
y = df["diagnosis"]

# 2. División train/test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# 3. Escalamiento
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)